export const movesKeyMap = () => ({
    "j": { move: "U" },
    "f": { move: "U'" },
    "i": { move: "R" },
    "k": { move: "R'" },
    "e": { move: "L'" },
    "d": { move: "L" },
    "h": { move: "F" },
    "g": { move: "F'" },
    "s": { move: "D" },
    "l": { move: "D'" },
    "w": { move: "B" },
    "o": { move: "B'" },
    ";": { move: "y" },
    "a": { move: "y'" },
    "n": { move: "x'" },
    "b": { move: "x'" },
    "y": { move: "x" },
    "t": { move: "x" },
    "q": { move: "z'" },
    "p": { move: "z" },
    "x": { move: "M'" },
    ",": { move: "M" },
    "u": { move: "r" },
    "m": { move: "r'" },
    "r": { move: "l'" },
    "v": { move: "l" }
})
